### Creating and Persisting an ML Model

In [15]:
import pandas as pd
import numpy as np
df = pd.read_csv('data/student-mat.csv', sep=';')

Summary of the data

In [16]:
df.describe()

df.corr()

/var/folders/95/wwsw3r1d7tjgj0tf7bbd5yvh0000gn/T/ipykernel_14732/1692572955.py:3: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
age,1.000000,-0.163658,-0.163438,0.070641,-0.004140,0.243665,0.053940,0.016434,0.126964,0.131125,0.117276,-0.062187,0.175230,-0.064081,-0.143474,-0.161579
Medu,-0.163658,1.000000,0.623455,-0.171639,0.064944,-0.236680,-0.003914,0.030891,0.064094,0.019834,-0.047123,-0.046878,0.100285,0.205341,0.215527,0.217147
Fedu,-0.163438,0.623455,1.000000,-0.158194,-0.009175,-0.250408,-0.001370,-0.012846,0.043105,0.002386,-0.012631,0.014742,0.024473,0.190270,0.164893,0.152457
traveltime,0.070641,-0.171639,-0.158194,1.000000,-0.100909,0.092239,-0.016808,-0.017025,0.028540,0.138325,0.134116,0.007501,-0.012944,-0.093040,-0.153198,-0.117142
studytime,-0.004140,0.064944,-0.009175,-0.100909,1.000000,-0.173563,0.039731,-0.143198,-0.063904,-0.196019,-0.253785,-0.075616,-0.062700,0.160612,0.135880,0.097820
failures,0.243665,-0.236680,-0.250408,0.092239,-0.173563,1.000000,-0.044337,0.091987,0.124561,0.136047,0.141962,0.065827,0.063726,-0.354718,-0.355896,-0.360415
famrel,0.053940,-0.003914,-0.001370,-0.016808,0.039731,-0.044337,1.000000,0.150701,0.064568,-0.077594,-0.113397,0.094056,-0.044354,0.022168,-0.018281,0.051363
freetime,0.016434,0.030891,-0.012846,-0.017025,-0.143198,0.091987,0.150701,1.000000,0.285019,0.209001,0.147822,0.075733,-0.058078,0.012613,-0.013777,0.011307
goout,0.126964,0.064094,0.043105,0.028540,-0.063904,0.124561,0.064568,0.285019,1.000000,0.266994,0.420386,-0.009577,0.044302,-0.149104,-0.162250,-0.132791
Dalc,0.131125,0.019834,0.002386,0.138325,-0.196019,0.136047,-0.077594,0.209001,0.266994,1.000000,0.647544,0.077180,0.111908,-0.094159,-0.064120,-0.054660
Walc,0.117276,-0.047123,-0.012631,0.134116,-0.253785,0.141962,-0.113397,0.147822,0.420386,0.647544,1.000000,0.092476,0.136291,-0.126179,-0.084927,-0.051939
health,-0.062187,-0.046878,0.014742,0.007501,-0.075616,0.065827,0.094056,0.075733,-0.009577,0.077180,0.092476,1.000000,-0.029937,-0.073172,-0.097720,-0.061335
absences,0.175230,0.100285,0.024473,-0.012944,-0.062700,0.063726,-0.044354,-0.058078,0.044302,0.111908,0.136291,-0.029937,1.000000,-0.031003,-0.031777,0.034247
G1,-0.064081,0.205341,0.190270,-0.093040,0.160612,-0.354718,0.022168,0.012613,-0.149104,-0.094159,-0.126179,-0.073172,-0.031003,1.000000,0.852118,0.801468
G2,-0.143474,0.215527,0.164893,-0.153198,0.135880,-0.355896,-0.018281,-0.013777,-0.162250,-0.064120,-0.084927,-0.097720,-0.031777,0.852118,1.000000,0.904868
G3,-0.161579,0.217147,0.152457,-0.117142,0.097820,-0.360415,0.051363,0.011307,-0.132791,-0.054660,-0.051939,-0.061335,0.034247,0.801468,0.904868,1.000000

In [4]:
df.info

<bound method DataFrame.info of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]>

Create a subset of features as an example.

In [17]:
include = ['G1', 'G2', 'absences','age','G3']
df.drop(columns=df.columns.difference(include), inplace=True)  # only using 3 features

In [18]:
df.info

<bound method DataFrame.info of      age  absences  G1  G2  G3
0     18         6   5   6   6
1     17         4   5   5   6
2     15        10   7   8  10
3     15         2  15  14  15
4     16         4   6  10  10
..   ...       ...  ..  ..  ..
390   20        11   9   9   9
391   17         3  14  16  16
392   21         3  10   8   7
393   18         0  11  12  10
394   19         5   8   9   9

[395 rows x 5 columns]>

The goal is to predict the quality of the student. We will build a predictor based on the final grade (G3).
Becasue we are trying to find quality students. In this model we define a quality student as one who achieves a final grade of 15 or higher.

In [19]:
df['qual_student'] = np.where(df['G3']>=15, 1, 0)

In [20]:
df.describe()

,age,absences,G1,G2,G3,qual_student
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,5.708861,10.908861,10.713924,10.415190,0.184810
std,1.276043,8.003096,3.319195,3.761505,4.581443,0.388636
min,15.000000,0.000000,3.000000,0.000000,0.000000,0.000000
25%,16.000000,0.000000,8.000000,9.000000,8.000000,0.000000
50%,17.000000,4.000000,11.000000,11.000000,11.000000,0.000000
75%,18.000000,8.000000,13.000000,13.000000,14.000000,0.000000
max,22.000000,75.000000,19.000000,19.000000,20.000000,1.000000

Drop the G3 score

In [21]:
include = ['G1', 'G2','absences', 'age','qual_student']
df.drop(columns=df.columns.difference(include), inplace=True)

Import scikit-learn and build a random forest classifer

In [26]:
from sklearn.ensemble import RandomForestClassifier as rf
import sklearn
dependent_variable = 'qual_student'
x = df[df.columns.difference([dependent_variable])]
y = df[dependent_variable]
clf = rf(n_estimators = 1000)
clf.fit(x, y)

RandomForestClassifier(n_estimators=1000)

In [27]:
pred = clf.predict(x)
sklearn.metrics.f1_score(y, pred, average='binary')

1.0

It's not very good! We didn't even cross validate. You'll need to do better :)
Let's export this model so we can use it in a microservice (flask api)

In [28]:
import joblib
# modify the file path to where you want to save the model
joblib.dump(clf, 'app/handlers/model.pkl')

['app/handlers/model.pkl']

In [31]:
query_df = pd.DataFrame({ 'age' : pd.Series(1) ,'G1' : 10 ,'G2' : 19 , 'absences' : pd.Series(10)})

In [32]:
pred = clf.predict(query_df)

/Users/phinguyen/.local/share/virtualenvs/fall-22-hw4-team-e2-CWter2ku/lib/python3.8/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

In [33]:
x

     G1  G2  absences  age
0     5   6         6   18
1     5   5         4   17
2     7   8        10   15
3    15  14         2   15
4     6  10         4   16
..   ..  ..       ...  ...
390   9   9        11   20
391  14  16         3   17
392  10   8         3   21
393  11  12         0   18
394   8   9         5   19

[395 rows x 4 columns]

In [34]:
type(x)

pandas.core.frame.DataFrame